#!/usr/bin/env python3

import geopandas as gpd
import networkx as nx
import matplotlib.pyplot as plt
import contextily as ctx

from pathfinder import djikstra, nearest_node, haversine, read_pois

if __name__ == "__main__":
	import os
	import argparse
	
    # Create argparser
	parser = argparse.ArgumentParser(description="Pathfinder script to process data and find paths.")

	# Arguments
	parser.add_argument('--data', '-d', required=True, help='Path to the input data file')
	parser.add_argument('--output', '-o', required=True, help='Path to the output file')

	parser.add_argument('--mode', '-m', default=None, help="Mode of operation: 'coord' for coordinates, or a path to a POIs file")

	parser.add_argument('--start', '-s', required=True, help='Start node/index')
	parser.add_argument('--end', '-e', required=True, help='End node/index')

	# Parse the arguments
	args = parser.parse_args()
	
    # Get data
	gdf = gpd.read_file(args.data)
	gdf = gdf[gdf.geometry.type.isin(["LineString", "MultiLineString"])]

	# Instantiate graph
	G = nx.Graph()

	# Populate graph
	for _, row in gdf.iterrows():
		coords = list(row.geometry.coords)
		
		for i in range(len(coords)-1):
			a = tuple(coords[i])
			b = tuple(coords[i+1])
			w = haversine(a, b)
			
			# Add edge and store name as edge attribute
			G.add_edge(a, b, weight=w)
	
	# Mode
	mode	= args.mode

	# Get start and end pts
	start	= args.start
	end     = args.end

	# Acquire coordinates based on mode
	if args.mode == 'coord':
		start_coord = tuple(map(float, start.split(',')))
		end_coord = tuple(map(float, end.split(',')))
	elif os.path.isfile(mode):
		pois = read_pois(mode)
		start_coord = pois[start.replace(' ', '_')]
		end_coord =   pois[end.replace(' ', '_')]
	else:
		raise Exception("Invalid mode. Choose from 'coord' (coordinate entry) and 'man' (named location entry).")

	# Locate nearest node on the path to start and end
	start_node = nearest_node(G, reversed(start_coord))
	end_node = nearest_node(G, reversed(end_coord))

	# Diagnostic output
	print(f"Start: {start_node} End: {end_node}")

	# Run djikstra and output
	
	"""
	min_len = float('inf');
	min_path = [];
	for s in start_nodes:
		for e in end_nodes:
			length, path = djikstra(G, s, e)
			if length < min_len:
				min_len = length
				min_path = path
	"""

	# min_path = []
	length, path = djikstra(G, start_node, end_node)
	print(f"Length: {length} m")

	print("Generating map...")
	
	# MPL output
	_, ax = plt.subplots(figsize=(10,10), dpi=200)

	# Plot all edges
	for u, v in G.edges:
		xs = [u[0], v[0]]
		ys = [u[1], v[1]]
		ax.plot(xs, ys, color='lightgray', linewidth=0.5)

	# Plot path
	path_x = [node[0] for node in path]
	path_y = [node[1] for node in path]
	ax.plot(path_x, path_y, color='red', linewidth=2, label='Shortest Path')

	ctx.add_basemap(ax, crs="EPSG:4326", source=ctx.providers.OpenStreetMap.Mapnik, zoom=17)

	# Add text
	ax.set_xlabel("Longitude")
	ax.set_ylabel("Latitude")
	ax.set_title(f"Shortest Path from {start} to {end}")
	ax.legend()

	# Save to output file
	plt.savefig(args.output)

	print(f"Map generated at {args.output}")
